# Generated by Django 3.2.3 on 2022-07-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='-', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
