# Generated by Django 3.2.3 on 2022-07-20 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_auto_20220719_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['post']},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='poll',
            name='total_votes',
            field=models.ManyToManyField(blank=True, related_name='blogpoll_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
