# Generated by Django 3.2.3 on 2022-07-21 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0006_remove_poll_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option1_value',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option2_value',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option3_value',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option4_value',
        ),
        migrations.AddField(
            model_name='poll',
            name='option1_voters',
            field=models.ManyToManyField(blank=True, related_name='poll_option1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='option2_voters',
            field=models.ManyToManyField(blank=True, related_name='poll_option2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='option3_voters',
            field=models.ManyToManyField(blank=True, related_name='poll_option3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='option4_voters',
            field=models.ManyToManyField(blank=True, related_name='poll_option4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='total_voters',
            field=models.ManyToManyField(blank=True, related_name='poll_total_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
